### ISSUE TITLE
Recent rendering changes?

### ISSUE THREAD

**Issue by ghost** [Im-dex/xray-162#16]
Hi,
First of all, just want to say it again: this repo is pure gold. I love the work you're doing here. I'm using this repo to build my mod Radium on if that's cool with you.

Anyway, after the March 20th commits I can no longer build a DirectX 11.3 device without error messages popping up in relation to dxgi1_1.h which I'm still trying to figure out.

To get to the point, some of these commits are enormous, can you give me a breakdown on any rendering changes you've made so I know where to troubleshoot?

Edit: Also, do you have an email you'd be willing to give me? I'd like to send you a message privately.

**Comment by ForserX** [comment]
Renderings have been modified in one of the first commits. Then, about AMD I'm-Dex asked me to check.

But this is not accurate. 
:)

**Comment by Im-dex** [comment]
@Swartz27 Hi! And thanks for warm words, glad to read this :)

About issue: I have done no changes especialy for the render. So I think that we should find first affected commit at first and then try figure out the reason of the issue. Most likely the problem is linked with cmake, maybe the incude paths settings became different (e.g. for DXSDK) and now code compiles a little bit different. I can try to investigate in this, If you write how to reproduce the issue.

PS: I've opened my email at profile.

**Comment by ghost** [comment]
I figured out the issue: I had to manually input the Windows 10 sdk directories :P

**Comment by Xottab-DUTY** [comment]
@Swartz27 I have almost the same problem with Win SDK. Can you say how you input it, please? Absolute path or some environment variable used?

**Comment by ghost** [comment]
I put in the absolute path, like C:/Program Files(x86)/Windows 10 sdk/include/um or whatever

**Comment by Xottab-DUTY** [comment]
@Swartz27 Thank you!

Sadly, but i can't find some env variable for win sdk, like dx sdk does. Will use absolute path for now)
